/* Music Fundamentals — master lesson list (source: AEMT Books 1-3 TOC, verified 2026-07-03)
   Drives ALL navigation. Titles/order locked to the textbook (DD-12). */
const LESSONS=[
 {n:1, title:"The Staff, Notes and Pitches", unit:1, book:1, time:15, kw:["staff","note","pitch","lines","spaces"]},
 {n:2, title:"Treble Clef and Staff", unit:1, book:1, time:12, kw:["treble","clef","G clef","EGBDF","FACE"]},
 {n:3, title:"Bass Clef and Staff", unit:1, book:1, time:12, kw:["bass","clef","F clef","GBDFA","ACEG"]},
 {n:4, title:"The Grand Staff and Ledger Lines (the middle notes)", unit:1, book:1, time:12, kw:["grand staff","ledger","middle C","brace"]},
 {n:5, title:"Ledger Lines (low and high notes)", unit:1, book:1, time:11, kw:["ledger","lines","high","low"]},
 {n:6, title:"Note Values", unit:2, book:1, time:11, kw:["whole","half","quarter","note values","rhythm"]},
 {n:7, title:"Measure, Bar Line and Double Bar", unit:2, book:1, time:10, kw:["measure","bar line","double bar"]},
 {n:8, title:"4/4 Time Signature and Note Values", unit:2, book:1, time:12, kw:["time signature","4/4","meter"]},
 {n:9, title:"Whole, Half and Quarter Rests", unit:2, book:1, time:11, kw:["rest","silence"]},
 {n:10, title:"2/4 Time Signature", unit:3, book:1, time:10, kw:["2/4","time signature"]},
 {n:11, title:"3/4 Time Signature", unit:3, book:1, time:10, kw:["3/4","waltz","time signature"]},
 {n:12, title:"Dotted Half Note", unit:3, book:1, time:10, kw:["dotted","half note","dot"]},
 {n:13, title:"Ties and Slurs", unit:3, book:1, time:11, kw:["tie","slur","legato"]},
 {n:14, title:"Repeat Sign, 1st and 2nd Endings", unit:4, book:1, time:10, kw:["repeat","endings"]},
 {n:15, title:"Eighth Notes", unit:4, book:1, time:12, kw:["eighth","beam","flag"]},
 {n:16, title:"Eighth Rests", unit:4, book:1, time:10, kw:["eighth rest"]},
 {n:17, title:"Dotted Quarter Note", unit:4, book:1, time:12, kw:["dotted quarter"]},
 {n:18, title:"Dynamic Signs", unit:5, book:1, time:10, kw:["dynamics","forte","piano","crescendo"]},
 {n:19, title:"Tempo Marks", unit:5, book:1, time:10, kw:["tempo","allegro","andante","adagio"]},
 {n:20, title:"Articulation", unit:5, book:1, time:10, kw:["staccato","accent","legato","fermata"]},
 {n:21, title:"D.C., D.S., Coda and Fine", unit:5, book:1, time:11, kw:["da capo","dal segno","coda","fine","road map"]},
 {n:22, title:"Flats", unit:6, book:1, time:10, kw:["flat","accidental"]},
 {n:23, title:"Sharps", unit:6, book:1, time:10, kw:["sharp","accidental"]},
 {n:24, title:"Naturals", unit:6, book:1, time:10, kw:["natural","accidental"]},
 {n:25, title:"Whole Steps, Half Steps and Enharmonic Notes", unit:6, book:1, time:13, kw:["whole step","half step","enharmonic"]},
 {n:26, title:"Tetrachords and Major Scales", unit:7, book:2, time:13, kw:["tetrachord","major scale"]},
 {n:27, title:"The Sharp Scales — G and D Major", unit:7, book:2, time:12, kw:["G major","D major","sharp scales"]},
 {n:28, title:"The Flat Scales — F and B♭ Major", unit:7, book:2, time:12, kw:["F major","Bb major","flat scales"]},
 {n:29, title:"Key Signatures — The Sharp Keys", unit:7, book:2, time:12, kw:["key signature","sharp keys"]},
 {n:30, title:"Key Signatures — The Flat Keys", unit:7, book:2, time:12, kw:["key signature","flat keys"]},
 {n:31, title:"The Remaining Major Scales with Key Signatures", unit:8, book:2, time:13, kw:["major scales","key signatures"]},
 {n:32, title:"Chromatic Scale", unit:8, book:2, time:11, kw:["chromatic","half steps"]},
 {n:33, title:"Intervals", unit:8, book:2, time:12, kw:["interval","2nd","3rd","distance"]},
 {n:34, title:"Circle of Fifths", unit:8, book:2, time:12, kw:["circle of fifths"]},
 {n:35, title:"Perfect and Major Intervals", unit:9, book:2, time:13, kw:["perfect","major","interval quality"]},
 {n:36, title:"Minor Intervals", unit:9, book:2, time:12, kw:["minor interval"]},
 {n:37, title:"Augmented and Diminished Intervals", unit:9, book:2, time:13, kw:["augmented","diminished","interval"]},
 {n:38, title:"Solfège and Transposition", unit:9, book:2, time:12, kw:["solfege","do re mi","transposition"]},
 {n:39, title:"Sixteenth Notes", unit:10, book:2, time:12, kw:["sixteenth","semiquaver"]},
 {n:40, title:"Sixteenth Rests", unit:10, book:2, time:10, kw:["sixteenth rest"]},
 {n:41, title:"Dotted Eighth Notes", unit:10, book:2, time:12, kw:["dotted eighth","swing"]},
 {n:42, title:"Common Time and Cut Time (Alla Breve)", unit:10, book:2, time:11, kw:["common time","cut time","alla breve"]},
 {n:43, title:"3/8 and 6/8 Time Signatures", unit:11, book:2, time:12, kw:["3/8","6/8","compound meter"]},
 {n:44, title:"3/8 and 6/8 Time Signatures at Fast Tempos", unit:11, book:2, time:11, kw:["6/8 fast","compound"]},
 {n:45, title:"Eighth Note Triplets", unit:11, book:2, time:12, kw:["triplet"]},
 {n:46, title:"Incomplete Measures (Pick-up Notes) and Syncopation", unit:11, book:2, time:12, kw:["pickup","anacrusis","syncopation"]},
 {n:47, title:"Triads", unit:12, book:2, time:13, kw:["triad","chord","root third fifth"]},
 {n:48, title:"Primary and Major Triads", unit:12, book:2, time:12, kw:["primary triads","I IV V"]},
 {n:49, title:"Scale Degree Names", unit:12, book:2, time:11, kw:["tonic","dominant","subdominant","scale degrees"]},
 {n:50, title:"The V7 (Dominant 7th) Chord", unit:12, book:2, time:12, kw:["V7","dominant seventh"]},
 {n:51, title:"Triads — 1st Inversion", unit:13, book:3, time:12, kw:["inversion","first inversion"]},
 {n:52, title:"Triads — 2nd Inversion", unit:13, book:3, time:12, kw:["second inversion"]},
 {n:53, title:"V7 Chord — 1st, 2nd and 3rd Inversions", unit:13, book:3, time:13, kw:["V7 inversions"]},
 {n:54, title:"Figured Bass", unit:13, book:3, time:13, kw:["figured bass","numbers"]},
 {n:55, title:"Major Chord Progressions", unit:13, book:3, time:12, kw:["progression","I IV V7"]},
 {n:56, title:"Minor Scales", unit:14, book:3, time:12, kw:["minor scale","relative minor"]},
 {n:57, title:"Natural, Harmonic and Melodic Minor Scales", unit:14, book:3, time:13, kw:["natural minor","harmonic minor","melodic minor"]},
 {n:58, title:"Minor Triads", unit:14, book:3, time:11, kw:["minor triad"]},
 {n:59, title:"Augmented and Diminished Triads", unit:14, book:3, time:12, kw:["augmented","diminished","triads"]},
 {n:60, title:"The Primary Triads in Minor Keys", unit:15, book:3, time:12, kw:["minor primary triads","i iv V"]},
 {n:61, title:"Minor Chord Progressions", unit:15, book:3, time:12, kw:["minor progression"]},
 {n:62, title:"Modes Related to the Major Scale: Ionian, Mixolydian and Lydian", unit:15, book:3, time:13, kw:["modes","ionian","mixolydian","lydian"]},
 {n:63, title:"Modes Related to the Minor Scale: Aeolian, Dorian, Phrygian, Locrian", unit:15, book:3, time:13, kw:["aeolian","dorian","phrygian","locrian"]},
 {n:64, title:"Harmonizing a Melody in a Major Key", unit:16, book:3, time:13, kw:["harmonize","melody","major"]},
 {n:65, title:"Broken Chords and Arpeggiated Accompaniments", unit:16, book:3, time:12, kw:["broken chord","arpeggio","alberti"]},
 {n:66, title:"Passing and Neighboring Tones", unit:16, book:3, time:12, kw:["passing tone","neighbor tone","nonharmonic"]},
 {n:67, title:"Composing a Melody in a Major Key", unit:16, book:3, time:13, kw:["compose","melody","major"]},
 {n:68, title:"Harmonizing a Melody in a Minor Key", unit:17, book:3, time:13, kw:["harmonize","minor"]},
 {n:69, title:"Composing a Melody in a Minor Key", unit:17, book:3, time:13, kw:["compose","minor"]},
 {n:70, title:"12-Bar Blues Chord Progression", unit:17, book:3, time:12, kw:["blues","12-bar"]},
 {n:71, title:"The Blues Scale", unit:17, book:3, time:11, kw:["blues scale"]},
 {n:72, title:"Basic Forms of Music — Motive and Phrase", unit:18, book:3, time:12, kw:["motive","phrase","form"]},
 {n:73, title:"AB (Binary) Form", unit:18, book:3, time:11, kw:["binary","AB form"]},
 {n:74, title:"ABA (Ternary) Form", unit:18, book:3, time:11, kw:["ternary","ABA form"]},
 {n:75, title:"Rondo Form", unit:18, book:3, time:12, kw:["rondo"]}
];
const UNITS=[
 {unit:1, book:1, name:"The Staff and Clefs", lessons:[1,5]},
 {unit:2, book:1, name:"Note Values and 4/4 Time", lessons:[6,9]},
 {unit:3, book:1, name:"More Time Signatures, Dots, Ties and Slurs", lessons:[10,13]},
 {unit:4, book:1, name:"Repeats, Eighth Notes and Dotted Quarters", lessons:[14,17]},
 {unit:5, book:1, name:"Expression Marks", lessons:[18,21]},
 {unit:6, book:1, name:"Accidentals and Steps", lessons:[22,25]},
 {unit:7, book:2, name:"Major Scales and Key Signatures", lessons:[26,30]},
 {unit:8, book:2, name:"Remaining Scales, Chromatic, Intervals, Circle of Fifths", lessons:[31,34]},
 {unit:9, book:2, name:"Interval Qualities, Solfège and Transposition", lessons:[35,38]},
 {unit:10, book:2, name:"Sixteenth Notes and Cut Time", lessons:[39,42]},
 {unit:11, book:2, name:"Compound Meter, Triplets and Syncopation", lessons:[43,46]},
 {unit:12, book:2, name:"Triads and the V7 Chord", lessons:[47,50]},
 {unit:13, book:3, name:"Inversions, Figured Bass and Progressions", lessons:[51,55]},
 {unit:14, book:3, name:"Minor Scales and Triad Qualities", lessons:[56,59]},
 {unit:15, book:3, name:"Minor Keys and Modes", lessons:[60,63]},
 {unit:16, book:3, name:"Harmonizing and Composing in Major", lessons:[64,67]},
 {unit:17, book:3, name:"Minor Harmonization and the Blues", lessons:[68,71]},
 {unit:18, book:3, name:"Form", lessons:[72,75]}
];
/* built lessons so far (index pages link only these) */
const BUILT_THROUGH=6;
const LESSON_CONTENT={}; /* filled by content/lesson-NN.js */
